### ISSUE TITLE
Cannot install extension

### ISSUE THREAD

**Issue by danifr** [jorgecarleitao/ipython-oidc-client#1] opened 2020-07-30 08:42 UTC
Hi Jorge,

I am following the steps described in the README but I am getting an error when enabling the serverextension.

```
(ipyauth_kernel) [root@jupyter ]# pip install ipython-oidc-client
Requirement already satisfied: ipython-oidc-client in /path/venvs/ipyauth_kernel/lib/python3.7/site-packages (0.1.2)
(ipyauth_kernel) [root@jupyter ]# 
(ipyauth_kernel) [root@jupyter ]# jupyter nbextension install --py ipython_oidc_client
Installing /path/venvs/ipyauth_kernel/lib/python3.7/site-packages/ipython_oidc_client/client -> ipython_oidc_client
Up to date: /usr/local/share/jupyter/nbextensions/ipython_oidc_client/main.js
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable ipython_oidc_client --py

(ipyauth_kernel) [root@jupyter ]# jupyter nbextension enable --py ipython_oidc_client
Enabling notebook extension ipython_oidc_client/main...
      - Validating: OK
(ipyauth_kernel) [root@jupyter ]# jupyter serverextension enable --py ipyoauth_oidc_client
Traceback (most recent call last):
  File "/path/venvs/ipyauth_kernel/bin/jupyter-serverextension", line 8, in <module>
    sys.exit(main())
  File "/path/venvs/ipyauth_kernel/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/path/venvs/ipyauth_kernel/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/path/venvs/ipyauth_kernel/lib/python3.7/site-packages/notebook/serverextensions.py", line 294, in start
    super(ServerExtensionApp, self).start()
  File "/path/venvs/ipyauth_kernel/lib/python3.7/site-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/path/venvs/ipyauth_kernel/lib/python3.7/site-packages/notebook/serverextensions.py", line 211, in start
    self.toggle_server_extension_python(arg)
  File "/path/venvs/ipyauth_kernel/lib/python3.7/site-packages/notebook/serverextensions.py", line 200, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/path/venvs/ipyauth_kernel/lib/python3.7/site-packages/notebook/serverextensions.py", line 328, in _get_server_extension_metadata
    m = import_item(module)
  File "/path/venvs/ipyauth_kernel/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'ipyoauth_oidc_client'
(ipyauth_kernel) [root@jupyter ]# 
```

Do you know what might be happening? These are the versions of the jupyter packages than I am running.
```
(ipyauth_kernel) [root@jupyter]# jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.5
ipython          : 7.16.1
ipykernel        : 5.3.0
jupyter client   : 6.1.6
jupyter lab      : 2.2.0
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3
```
Thanks a lot!

**Comment by jorgecarleitao** [comment] 2020-07-30 17:49
Hi Daniel,

I am sorry that you were unable to install this package.

I am unable to reproduce your error. Specifically, I used the Dockerfile on the project to have a reproducible build:

```
git clone git@github.com:jorgecarleitao/ipython-oidc-client.git
cd ipython-oidc-client
docker build -t t .
```

and it builds correctly. I tried to reproduce your environment by using:

* a venv
* install jupyterlab
* not pass `--system` to the calls:

```
FROM python:3.7.4-buster

RUN python -m venv venv
RUN . venv/bin/activate

RUN pip install jupyter
RUN pip install jupyterlab

RUN jupyter --version

RUN pip install ipython_oidc_client

RUN    jupyter nbextension install --py ipython_oidc_client \
    && jupyter nbextension enable --py ipython_oidc_client \
    && jupyter serverextension enable --py ipython_oidc_client
```

which gives me a setup very close to yours:

```
Step 6/13 : RUN jupyter --version
 ---> Running in 33090cb48286
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.5
ipython          : 7.16.1
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : 2.2.2
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```

but gives me no error. Is there any thing that you think could be different from the setup declared on the Dockerfile above?

**Comment by danifr** [comment] 2020-07-31 09:33
Ahhh sorry there was a tiny typo in the README

https://github.com/jorgecarleitao/ipython-oidc-client/pull/2

**Comment by jorgecarleitao** [comment] 2020-07-31 09:45
Damm, sorry about that and thanks for the fix!

Feel free to close this one if the problem is solved.

**Closed as completed** 2020-07-31 09:56 UTC
